### ISSUE TITLE
Upload a Video

### ISSUE THREAD

**Issue by fabiananillo** [sr1871/yii2-youtube-api#1]
How I can upload a video using this component?

**Comment by sr1871** [comment]
> How I can upload a video using this component?

After make all the configuration that be in [readme](https://github.com/sr1871/yii2-youtube-api) , [refer to uploadVideo method](https://github.com/sr1871/yii2-youtube-api/blob/master/src/components/YoutubeApi.php#L161) in youtubeApi component.

for see the parameters you can pass in snippetData  or status see https://developers.google.com/youtube/v3/docs/videos/insert?hl=en-419#request-body

An example could be `
Yii::$app->youtube->uploadVideo('/path/the/video', 
     [
        'title' => 'video title',  
         'description' => 'description of the video' 
     ], 
     ['privacyStatus' => 'public']);`
